# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
- develop
- releases/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  disable.coverage.autogenerate: 'true'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --logger trx --collect "XPlat Code Coverage" --results-directory $(Build.SourcesDirectory)\TestResults'
    publishTestResults: false

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    searchFolder: '$(Build.SourcesDirectory)\TestResults'
    buildPlatform: '$(buildPlatform)'
    buildConfiguration: '$(buildConfiguration)'

- task: reportgenerator@4
  inputs:
    reports: 'TestResults\*\coverage.cobertura.xml'
    targetdir: 'TestResults\report'
    reporttypes: 'HtmlInline_AzurePipelines;Cobertura;Badges'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)\TestResults\report\Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)\TestResults\report'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**\Calculator\*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    zipAfterPublish: false

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)\Calculator\bin\$(buildConfiguration)\*\win-x64\publish'
    artifact: 'Application'
    publishLocation: 'pipeline'